apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: demo
spec:
  replicas: 2
  selector: { matchLabels: { app: demo } }
  template:
    metadata: { labels: { app: demo } }
    spec:
      containers:
        - name: web
          image: docker.io/hyeyeon763/java
          ports: [{ containerPort: 8000 }]
      # (private면)
      # imagePullSecrets:
      #   - name: regcred
