apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  namespace: demo
spec:
  replicas: 2
  selector: { matchLabels: { app: demo } }
  template:
    metadata: { labels: { app: demo } }
    spec:
      containers:
        - name: web
          image: docker.io/hyeyeon763/ec2:0.0.1 # 이름/레포 "hyeyeon763/ec2"로 고정
          ports: [{ containerPort: 8000 }]
      # (private면)
      # imagePullSecrets:
      #   - name: regcred
